# Generated by Django 4.2.7 on 2024-02-24 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='description',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='application',
            name='annual_salary',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='annual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='bonus_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='employment_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='must_have',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
