# Generated by Django 4.2.7 on 2024-02-25 13:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_alter_joblisting_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='bonus_skills',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='must_have',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='qualifications',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='responsibilities',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='summary',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
