# Generated by Django 4.2.7 on 2024-02-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0005_alter_joblisting_country_alter_joblisting_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.FileField(default='txt.pdf', upload_to='pdfs/cover_letters'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(default='txt.pdf', upload_to='pdfs/resumes'),
        ),
    ]
